**Tratamento de dados | Simulando planilha SAP**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/18rCSRLgcialsF8pAw-z6AAPbCkK-DpXorpvUaCBF0lc/export?format=csv")

In [ ]:
df.head()

,Empresa,Documento,Data,Conta,CentroCusto,Descricao,Debito,Credito,Moeda,Usuario
0,1000,5100001234,10/07/2024,410000,CC1000,Material Escritório,1500.0,NaN,BRL,NAIANE.BARB
1,1000,5100001235,10/07/2024,420000,CC1001,Serviço Limpeza,3500.0,NaN,BRL,MARIA.LIMA
2,1000,5100001236,11/07/2024,211000,CC1000,Pagamento fornecedor,NaN,2500.0,BRL,JOAO.COSTA
3,1000,5100001237,11/07/2024,500100,CC1002,Viagem Nacional,1250.0,NaN,BRL,ANA.SOUZA
4,2000,6100002345,12/07/2024,220000,CC2000,Recebimento Cliente,NaN,5500.0,USD,CARLOS.ALVE

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Empresa      8 non-null      int64
 1   Documento    8 non-null      int64
 2   Data         8 non-null      object
 3   Conta        8 non-null      int64
 4   CentroCusto  8 non-null      object
 5   Descricao    8 non-null      object
 6   Debito       5 non-null      float64
 7   Credito      3 non-null      float64
 8   Moeda        8 non-null      object
 9   Usuario      8 non-null      object
dtypes: float64(2), int64(3), object(5)
memory usage: 772.0+ bytes

In [ ]:
df.describe()

           Empresa     Documento          Conta       Debito      Credito
count     8.000000  8.000000e+00       8.000000     5.000000     3.000000
mean   1500.000000  5.600002e+09  360350.000000  2590.000000  3933.333333
std     534.522484  5.345231e+08  126342.120564  1266.096363  1504.437880
min    1000.000000  5.100001e+09  211000.000000  1250.000000  2500.000000
25%    1000.000000  5.100001e+09  217875.000000  1500.000000  3150.000000
50%    1500.000000  5.600002e+09  410000.000000  2500.000000  3800.000000
75%    2000.000000  6.100002e+09  440025.000000  3500.000000  4650.000000
max    2000.000000  6.100002e+09  500200.000000  4200.000000  5500.000000

In [ ]:
df.columns

Index(['Empresa', 'Documento', 'Data', 'Conta', 'CentroCusto', 'Descricao',
       'Debito', 'Credito', 'Moeda', 'Usuario'],
      dtype='object')

In [ ]:
df["Data"].value_counts()

Data
10/07/2024    2
11/07/2024    2
12/07/2024    2
13/07/2024    1
14/07/2024    1
Name: count, dtype: int64

In [ ]:
df["Usuario"].value_counts()

Usuario
NAIANE.BARB     1
MARIA.LIMA      1
JOAO.COSTA      1
ANA.SOUZA       1
CARLOS.ALVE     1
MARCELO.RIBE    1
PAULA.SILVA     1
FERNANDA.MOR    1
Name: count, dtype: int64

In [ ]:
df[df["Descricao"].isnull()]

Empty DataFrame
Columns: [Empresa, Documento, Data, Conta, CentroCusto, Descricao, Debito, Credito, Moeda, Usuario]
Index: []